package gameconstants

type Hero uint32

var HeroInternalNames = map[string]string{
  "abaddon": "Abaddon",
  "alchemist": "Alchemist",
  "ancient_apparition": "Ancient Apparition",
  "antimage": "Anti-Mage",
  "arc_warden": "Arc Warden",
  "axe": "Axe",
  "bane": "Bane",
  "batrider": "Batrider",
  "beastmaster": "Beastmaster",
  "bloodseeker": "Bloodseeker",
  "bounty_hunter": "Bounty Hunter",
  "brewmaster": "Brewmaster",
  "bristleback": "Bristleback",
  "broodmother": "Broodmother",
  "centaur": "Centaur Warrunner",
  "chaos_knight": "Chaos Knight",
  "chen": "Chen",
  "clinkz": "Clinkz",
  "crystal_maiden": "Crystal Maiden",
  "dark_seer": "Dark Seer",
  "dazzle": "Dazzle",
  "death_prophet": "Death Prophet",
  "disruptor": "Disruptor",
  "doom_bringer": "Doom",
  "dragon_knight": "Dragon Knight",
  "drow_ranger": "Drow Ranger",
  "earth_spirit": "Earth Spirit",
  "earthshaker": "Earthshaker",
  "elder_titan": "Elder Titan",
  "ember_spirit": "Ember Spirit",
  "enchantress": "Enchantress",
  "enigma": "Enigma",
  "faceless_void": "Faceless Void",
  "furion": "Nature's Prophet",
  "gyrocopter": "Gyrocopter",
  "huskar": "Huskar",
  "invoker": "Invoker",
  "jakiro": "Jakiro",
  "juggernaut": "Juggernaut",
  "keeper_of_the_light": "Keeper of the Light",
  "kunkka": "Kunkka",
  "legion_commander": "Legion Commander",
  "leshrac": "Leshrac",
  "lich": "Lich",
  "life_stealer": "Lifestealer",
  "lina": "Lina",
  "lion": "Lion",
  "lone_druid": "Lone Druid",
  "luna": "Luna",
  "lycan": "Lycan",
  "magnataur": "Magnus",
  "medusa": "Medusa",
  "meepo": "Meepo",
  "mirana": "Mirana",
  "morphling": "Morphling",
  "naga_siren": "Naga Siren",
  "necrolyte": "Necrophos",
  "nevermore": "Shadow Fiend",
  "night_stalker": "Night Stalker",
  "nyx_assassin": "Nyx Assassin",
  "obsidian_destroyer": "Outworld Devourer",
  "ogre_magi": "Ogre Magi",
  "omniknight": "Omniknight",
  "phantom_assassin": "Phantom Assassin",
  "phantom_lancer": "Phantom Lancer",
  "phoenix": "Phoenix",
  "puck": "Puck",
  "pudge": "Pudge",
  "pugna": "Pugna",
  "queenofpain": "Queen of Pain",
  "rattletrap": "Clockwerk",
  "razor": "Razor",
  "riki": "Riki",
  "rubick": "Rubick",
  "sand_king": "Sand King",
  "shadow_demon": "Shadow Demon",
  "shadow_shaman": "Shadow Shaman",
  "shredder": "Timbersaw",
  "silencer": "Silencer",
  "skeleton_king": "Wraith King",
  "skywrath_mage": "Skywrath Mage",
  "slardar": "Slardar",
  "slark": "Slark",
  "sniper": "Sniper",
  "spectre": "Spectre",
  "spirit_breaker": "Spirit Breaker",
  "storm_spirit": "Storm Spirit",
  "sven": "Sven",
  "templar_assassin": "Templar Assassin",
  "terrorblade": "Terrorblade",
  "tidehunter": "Tidehunter",
  "tinker": "Tinker",
  "tiny": "Tiny",
  "treant": "Treant Protector",
  "troll_warlord": "Troll Warlord",
  "tusk": "Tusk",
  "undying": "Undying",
  "ursa": "Ursa",
  "vengefulspirit": "Vengeful Spirit",
  "venomancer": "Venomancer",
  "viper": "Viper",
  "visage": "Visage",
  "warlock": "Warlock",
  "weaver": "Weaver",
  "windrunner": "Windranger",
  "wisp": "Wisp",
  "witch_doctor": "Witch Doctor",
  "zuus": "Zeus",
}

var HeroNames = map[uint32]string{
  1: "Anti-Mage",
  2: "Axe",
  3: "Bane",
  4: "Bloodseeker",
  5: "Crystal Maiden",
  6: "Drow Ranger",
  7: "Earthshaker",
  8: "Juggernaut",
  9: "Mirana",
  10: "Morphling",
  11: "Shadow Fiend",
  12: "Phantom Lancer",
  13: "Puck",
  14: "Pudge",
  15: "Razor",
  16: "Sand King",
  17: "Storm Spirit",
  18: "Sven",
  19: "Tiny",
  20: "Vengeful Spirit",
  21: "Windranger",
  22: "Zeus",
  23: "Kunkka",
  25: "Lina",
  26: "Lion",
  27: "Shadow Shaman",
  28: "Slardar",
  29: "Tidehunter",
  30: "Witch Doctor",
  31: "Lich",
  32: "Riki",
  33: "Enigma",
  34: "Tinker",
  35: "Sniper",
  36: "Necrophos",
  37: "Warlock",
  38: "Beastmaster",
  39: "Queen of Pain",
  40: "Venomancer",
  41: "Faceless Void",
  42: "Wraith King",
  43: "Death Prophet",
  44: "Phantom Assassin",
  45: "Pugna",
  46: "Templar Assassin",
  47: "Viper",
  48: "Luna",
  49: "Dragon Knight",
  50: "Dazzle",
  51: "Clockwerk",
  52: "Leshrac",
  53: "Nature's Prophet",
  54: "Lifestealer",
  55: "Dark Seer",
  56: "Clinkz",
  57: "Omniknight",
  58: "Enchantress",
  59: "Huskar",
  60: "Night Stalker",
  61: "Broodmother",
  62: "Bounty Hunter",
  63: "Weaver",
  64: "Jakiro",
  65: "Batrider",
  66: "Chen",
  67: "Spectre",
  68: "Ancient Apparition",
  69: "Doom",
  70: "Ursa",
  71: "Spirit Breaker",
  72: "Gyrocopter",
  73: "Alchemist",
  74: "Invoker",
  75: "Silencer",
  76: "Outworld Devourer",
  77: "Lycan",
  78: "Brewmaster",
  79: "Shadow Demon",
  80: "Lone Druid",
  81: "Chaos Knight",
  82: "Meepo",
  83: "Treant Protector",
  84: "Ogre Magi",
  85: "Undying",
  86: "Rubick",
  87: "Disruptor",
  88: "Nyx Assassin",
  89: "Naga Siren",
  90: "Keeper of the Light",
  91: "Wisp",
  92: "Visage",
  93: "Slark",
  94: "Medusa",
  95: "Troll Warlord",
  96: "Centaur Warrunner",
  97: "Magnus",
  98: "Timbersaw",
  99: "Bristleback",
  100: "Tusk",
  101: "Skywrath Mage",
  102: "Abaddon",
  103: "Elder Titan",
  104: "Legion Commander",
  105: "Techies",
  106: "Ember Spirit",
  107: "Earth Spirit",
  108: "Abyssal Underlord",
  109: "Terrorblade",
  110: "Phoenix",
  111: "Oracle",
  113: "Arc Warden",
}
